// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awgkohazhjewjtsirjqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Z2tvaGF6aGpld2p0c2lyanFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTg3MDcsImV4cCI6MjA1OTI5NDcwN30.gcG2gY_avjNNKzbILBxzmqxN49jwqES8IU655gU4hpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);